### ISSUE TITLE
Setup Submission, Anecdote and Research Forms

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage#11]
Please do this ticket first: https://github.com/ContextualCamouflage/contextual-camoflage/issues/9

- We need to setup each form progressive flow (order is Submission, Anecdote, Research)
- Setup proper dropdowns (look at CC v1 for the data needed)
- Submit the cookie on each form submission, Backend will handle the IP address
- Allow the user to exit out of the flow if they do not want to add an Anecdote or Research 
- Keep them on the page

**Comment by danigirl329** [comment]
I will set a cookie on "Share my Story"
Reset the cookie anytime I'm finished is clicked
Keep the cookie small like _cc
Randomize the value of the cookie
