### ISSUE TITLE
Implement Custom Icons for Leaflet 

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage#15]
We need to design, then link to the marker class for each submission illness type. I think if we use a wavy blog top icon, it will end up looking like camoflage. 

They should match the current key: 

![screen shot 2017-07-22 at 3 34 48 pm](https://user-images.githubusercontent.com/2446523/28494121-59280524-6ef3-11e7-82fd-30100650f54d.png)

The actual colors are linked here: 

https://github.com/ContextualCamouflage/contextual-camoflage/blob/90624d74f6bd93a2ba61d26fc535e93946f1f47e/app/assets/stylesheets/general/theme.scss

**Comment by jwaltrowski** [comment]
https://drive.google.com/open?id=0B77jfrlLDg2jaGNLQ1ZqY2JTRW8
