### ISSUE TITLE
Implement Leaflet Gem for Installation Views of Illnesses 

### ISSUE THREAD

**Issue by wonderwoman13** [ContextualCamouflage/contextual-camoflage#2]
I plan on pairing with @danigirl329 on this. 

https://github.com/axyjo/leaflet-rails

**Comment by wonderwoman13** [comment]
Example not using the gem with Rails: http://womanonrails.com/leaflet

**Comment by wonderwoman13** [comment]
Ruby Gem to wrap leaflet library: https://github.com/cfis/leaflet-js

**Comment by danigirl329** [comment]
You can work on this branch: https://github.com/ContextualCamouflage/contextual-camoflage/tree/try-leaflet
